# Generated by Django 4.2.1 on 2023-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetic_algorithm', '0002_alter_individual_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='generation',
            field=models.IntegerField(default=0),
        ),
    ]
